### ISSUE TITLE
Add a version and creation field on NN objects

### ISSUE THREAD

**Issue by joapaspe** [pakozm/april-ann#134]
Like Matlab, it would be interesting to add the version and other important data about how the Neural Network (trainable) object have been created.

Matlab uses a format like
MATLAB 5.0 MAT-file Platform: posix, Created on: Tue Mar  3 12:45:37 2015

We could uses dictionary fields within the objects like:
april-version
april-compilation
time-stamp

It will be used in the future for asserts and warnings about compatibility issues.

**Comment by pakozm** [comment]
I find this useful when loading models from disk or other kind of serialized storage. This information can be stored within the serialized object, so during deserialization this information can be retrieved and given to the user program.

**Comment by pakozm** [comment]
What about something like this?

```Lua
> print( util.serialize({1, 2, 3, a="Hello World"}) )
return {1,2,3,["a"]="Hello World"},
-- version info { major, minor, commit number, commit hash, date }
{0,4,"2436","6e343d3e624ee553a32d6526ff841c4a1753344d","Tue Mar 10 14:46:34 2015"}
```

It doesn't use a dictionary, just an array table because it is just the output of `util.version()` function with the addition of the date at the end. This information would be at the end of every serialized object. Just remember to use `util.serialize(object, filename)` instead of the save method available in some objects.

I have committed a new branch (commit 665d0c7) with this solution, it is easy and can be merged when we agree.

**Comment by joapaspe** [comment]
Why don't add the version info in the save methods?

**Comment by pakozm** [comment]
Because each save method is a specific case, there is not a general way to do that. Indeed, they would be marked as deprecated in the future, just to be replaced by `util.serialize()` and `util.deserialize()`.

**Comment by joapaspe** [comment]
Yes. But, for example I use load and save for trainers. What would be the difference of them being a wrapper over trainable?

**Comment by pakozm** [comment]
Its exactly the same, `util.serialize()` and `util.deserialize()` are a general way of save and load. Indeed, `util.deserialize()` is just a call to Lua `dofile()` function. I recommended to do a transition to new methods. It is possible to replace the save/load implementation and put there a call to util functions, but think about that save/load they would disappear in some point in the future.

**Comment by pakozm** [comment]
`trainable.save` has been updated to be `util.serialize`, so it is possible to continue using the old `save` method ;-) but it would be deprecated soon...
